import { Employee } from "./models/employee.model";

export const employees: Employee[] = [
  {
    id: 1,
    username: "john.doe",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    birthDate: "1990-01-15",
    basicSalary: 4500000,
    status: "Active",
    group: "Engineering",
    description: "Frontend Developer"
  },
  {
    id: 2,
    username: "jane.smith",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    birthDate: "1992-05-20",
    basicSalary: 5000000,
    status: "Active",
    group: "Engineering",
    description: "Backend Developer"
  },
  {
    id: 3,
    username: "bob.johnson",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    birthDate: "1985-11-08",
    basicSalary: 6000000,
    status: "Active",
    group: "Management",
    description: "Project Manager"
  },
  {
    id: 4,
    username: "alice.williams",
    firstName: "Alice",
    lastName: "Williams",
    email: "alice.williams@example.com",
    birthDate: "1988-07-30",
    basicSalary: 5500000,
    status: "Inactive",
    group: "Design",
    description: "UI/UX Designer"
  },
  {
    id: 5,
    username: "charlie.brown",
    firstName: "Charlie",
    lastName: "Brown",
    email: "charlie.brown@example.com",
    birthDate: "1993-03-12",
    basicSalary: 4800000,
    status: "Active",
    group: "Engineering",
    description: "QA Engineer"
  },
  {
    id: 6,
    username: "emma.davis",
    firstName: "Emma",
    lastName: "Davis",
    email: "emma.davis@example.com",
    birthDate: "1991-09-25",
    basicSalary: 4700000,
    status: "Active",
    group: "Marketing",
    description: "Digital Marketing Specialist"
  },
  {
    id: 7,
    username: "michael.wilson",
    firstName: "Michael",
    lastName: "Wilson",
    email: "michael.wilson@example.com",
    birthDate: "1987-06-14",
    basicSalary: 5200000,
    status: "Active",
    group: "Engineering",
    description: "DevOps Engineer"
  },
  {
    id: 8,
    username: "olivia.taylor",
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@example.com",
    birthDate: "1994-02-28",
    basicSalary: 4300000,
    status: "Active",
    group: "HR",
    description: "HR Coordinator"
  },
  {
    id: 9,
    username: "william.anderson",
    firstName: "William",
    lastName: "Anderson",
    email: "william.anderson@example.com",
    birthDate: "1989-12-10",
    basicSalary: 5800000,
    status: "Active",
    group: "Finance",
    description: "Financial Analyst"
  },
  {
    id: 10,
    username: "sophia.martinez",
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia.martinez@example.com",
    birthDate: "1993-08-05",
    basicSalary: 4600000,
    status: "Active",
    group: "Design",
    description: "Graphic Designer"
  },
  {
    id: 11,
    username: "james.thompson",
    firstName: "James",
    lastName: "Thompson",
    email: "james.thompson@example.com",
    birthDate: "1986-04-19",
    basicSalary: 5500000,
    status: "Active",
    group: "Engineering",
    description: "System Architect"
  },
  {
    id: 12,
    username: "ava.garcia",
    firstName: "Ava",
    lastName: "Garcia",
    email: "ava.garcia@example.com",
    birthDate: "1992-11-22",
    basicSalary: 4800000,
    status: "Inactive",
    group: "Marketing",
    description: "Content Writer"
  },
  {
    id: 13,
    username: "alexander.robinson",
    firstName: "Alexander",
    lastName: "Robinson",
    email: "alexander.robinson@example.com",
    birthDate: "1988-03-17",
    basicSalary: 5300000,
    status: "Active",
    group: "Engineering",
    description: "Mobile Developer"
  },
  {
    id: 14,
    username: "mia.clark",
    firstName: "Mia",
    lastName: "Clark",
    email: "mia.clark@example.com",
    birthDate: "1995-07-09",
    basicSalary: 4200000,
    status: "Active",
    group: "Operations",
    description: "Operations Coordinator"
  },
  {
    id: 15,
    username: "ethan.rodriguez",
    firstName: "Ethan",
    lastName: "Rodriguez",
    email: "ethan.rodriguez@example.com",
    birthDate: "1990-10-31",
    basicSalary: 5100000,
    status: "Active",
    group: "Engineering",
    description: "Data Engineer"
  },
  {
    id: 16,
    username: "isabella.lewis",
    firstName: "Isabella",
    lastName: "Lewis",
    email: "isabella.lewis@example.com",
    birthDate: "1993-01-24",
    basicSalary: 4700000,
    status: "Active",
    group: "Finance",
    description: "Accountant"
  },
  {
    id: 17,
    username: "daniel.lee",
    firstName: "Daniel",
    lastName: "Lee",
    email: "daniel.lee@example.com",
    birthDate: "1987-05-12",
    basicSalary: 5600000,
    status: "Active",
    group: "Engineering",
    description: "Security Engineer"
  },
  {
    id: 18,
    username: "charlotte.walker",
    firstName: "Charlotte",
    lastName: "Walker",
    email: "charlotte.walker@example.com",
    birthDate: "1994-09-03",
    basicSalary: 4500000,
    status: "Inactive",
    group: "HR",
    description: "Recruitment Specialist"
  },
  {
    id: 19,
    username: "matthew.hall",
    firstName: "Matthew",
    lastName: "Hall",
    email: "matthew.hall@example.com",
    birthDate: "1989-02-18",
    basicSalary: 5200000,
    status: "Active",
    group: "Management",
    description: "Team Lead"
  },
  {
    id: 20,
    username: "amelia.allen",
    firstName: "Amelia",
    lastName: "Allen",
    email: "amelia.allen@example.com",
    birthDate: "1992-12-07",
    basicSalary: 4600000,
    status: "Active",
    group: "Design",
    description: "Product Designer"
  },
  {
    id: 21,
    username: "joseph.young",
    firstName: "Joseph",
    lastName: "Young",
    email: "joseph.young@example.com",
    birthDate: "1988-08-23",
    basicSalary: 5100000,
    status: "Active",
    group: "Engineering",
    description: "Full Stack Developer"
  },
  {
    id: 22,
    username: "victoria.king",
    firstName: "Victoria",
    lastName: "King",
    email: "victoria.king@example.com",
    birthDate: "1991-04-15",
    basicSalary: 4900000,
    status: "Active",
    group: "Marketing",
    description: "Marketing Manager"
  },
  {
    id: 23,
    username: "benjamin.wright",
    firstName: "Benjamin",
    lastName: "Wright",
    email: "benjamin.wright@example.com",
    birthDate: "1986-11-29",
    basicSalary: 5700000,
    status: "Active",
    group: "Management",
    description: "Product Manager"
  },
  {
    id: 24,
    username: "emily.lopez",
    firstName: "Emily",
    lastName: "Lopez",
    email: "emily.lopez@example.com",
    birthDate: "1993-06-07",
    basicSalary: 4400000,
    status: "Inactive",
    group: "HR",
    description: "HR Assistant"
  },
  {
    id: 25,
    username: "christopher.hill",
    firstName: "Christopher",
    lastName: "Hill",
    email: "christopher.hill@example.com",
    birthDate: "1989-09-14",
    basicSalary: 5300000,
    status: "Active",
    group: "Engineering",
    description: "Cloud Engineer"
  },
  {
    id: 26,
    username: "abigail.scott",
    firstName: "Abigail",
    lastName: "Scott",
    email: "abigail.scott@example.com",
    birthDate: "1994-01-31",
    basicSalary: 4600000,
    status: "Active",
    group: "Design",
    description: "UX Researcher"
  },
  {
    id: 27,
    username: "andrew.green",
    firstName: "Andrew",
    lastName: "Green",
    email: "andrew.green@example.com",
    birthDate: "1987-03-26",
    basicSalary: 5500000,
    status: "Active",
    group: "Engineering",
    description: "Database Administrator"
  },
  {
    id: 28,
    username: "elizabeth.adams",
    firstName: "Elizabeth",
    lastName: "Adams",
    email: "elizabeth.adams@example.com",
    birthDate: "1992-07-19",
    basicSalary: 4800000,
    status: "Active",
    group: "Finance",
    description: "Finance Coordinator"
  },
  {
    id: 29,
    username: "david.baker",
    firstName: "David",
    lastName: "Baker",
    email: "david.baker@example.com",
    birthDate: "1990-05-02",
    basicSalary: 5000000,
    status: "Active",
    group: "Engineering",
    description: "Infrastructure Engineer"
  },
  {
    id: 30,
    username: "sofia.gonzalez",
    firstName: "Sofia",
    lastName: "Gonzalez",
    email: "sofia.gonzalez@example.com",
    birthDate: "1995-10-11",
    basicSalary: 4300000,
    status: "Active",
    group: "Marketing",
    description: "Social Media Specialist"
  },
  {
    id: 31,
    username: "joseph.nelson",
    firstName: "Joseph",
    lastName: "Nelson",
    email: "joseph.nelson@example.com",
    birthDate: "1988-12-04",
    basicSalary: 5200000,
    status: "Active",
    group: "Engineering",
    description: "Backend Developer"
  },
  {
    id: 32,
    username: "madison.carter",
    firstName: "Madison",
    lastName: "Carter",
    email: "madison.carter@example.com",
    birthDate: "1993-02-22",
    basicSalary: 4700000,
    status: "Inactive",
    group: "Design",
    description: "Motion Designer"
  },
  {
    id: 33,
    username: "samuel.mitchell",
    firstName: "Samuel",
    lastName: "Mitchell",
    email: "samuel.mitchell@example.com",
    birthDate: "1989-07-16",
    basicSalary: 5400000,
    status: "Active",
    group: "Management",
    description: "Technical Lead"
  },
  {
    id: 34,
    username: "avery.perez",
    firstName: "Avery",
    lastName: "Perez",
    email: "avery.perez@example.com",
    birthDate: "1994-11-08",
    basicSalary: 4500000,
    status: "Active",
    group: "Operations",
    description: "Business Analyst"
  },
  {
    id: 35,
    username: "henry.roberts",
    firstName: "Henry",
    lastName: "Roberts",
    email: "henry.roberts@example.com",
    birthDate: "1991-06-30",
    basicSalary: 4900000,
    status: "Active",
    group: "Engineering",
    description: "Frontend Developer"
  },
  {
    id: 36,
    username: "scarlett.turner",
    firstName: "Scarlett",
    lastName: "Turner",
    email: "scarlett.turner@example.com",
    birthDate: "1993-09-12",
    basicSalary: 4600000,
    status: "Active",
    group: "HR",
    description: "Training Coordinator"
  },
  {
    id: 37,
    username: "sebastian.phillips",
    firstName: "Sebastian",
    lastName: "Phillips",
    email: "sebastian.phillips@example.com",
    birthDate: "1987-01-27",
    basicSalary: 5600000,
    status: "Active",
    group: "Engineering",
    description: "Software Architect"
  },
  {
    id: 38,
    username: "lily.campbell",
    firstName: "Lily",
    lastName: "Campbell",
    email: "lily.campbell@example.com",
    birthDate: "1992-04-05",
    basicSalary: 4700000,
    status: "Active",
    group: "Finance",
    description: "Budget Analyst"
  },
  {
    id: 39,
    username: "jackson.parker",
    firstName: "Jackson",
    lastName: "Parker",
    email: "jackson.parker@example.com",
    birthDate: "1990-08-18",
    basicSalary: 5100000,
    status: "Active",
    group: "Engineering",
    description: "QA Lead"
  },
  {
    id: 40,
    username: "grace.evans",
    firstName: "Grace",
    lastName: "Evans",
    email: "grace.evans@example.com",
    birthDate: "1995-03-21",
    basicSalary: 4400000,
    status: "Active",
    group: "Marketing",
    description: "Content Strategist"
  },
  {
    id: 41,
    username: "leo.edwards",
    firstName: "Leo",
    lastName: "Edwards",
    email: "leo.edwards@example.com",
    birthDate: "1988-02-14",
    basicSalary: 5300000,
    status: "Active",
    group: "Engineering",
    description: "Machine Learning Engineer"
  },
  {
    id: 42,
    username: "hannah.collins",
    firstName: "Hannah",
    lastName: "Collins",
    email: "hannah.collins@example.com",
    birthDate: "1993-10-09",
    basicSalary: 4600000,
    status: "Active",
    group: "Design",
    description: "Interaction Designer"
  },
  {
    id: 43,
    username: "ryan.stewart",
    firstName: "Ryan",
    lastName: "Stewart",
    email: "ryan.stewart@example.com",
    birthDate: "1986-07-23",
    basicSalary: 5800000,
    status: "Active",
    group: "Management",
    description: "Engineering Manager"
  },
  {
    id: 44,
    username: "zoe.sanchez",
    firstName: "Zoe",
    lastName: "Sanchez",
    email: "zoe.sanchez@example.com",
    birthDate: "1994-05-17",
    basicSalary: 4500000,
    status: "Inactive",
    group: "Marketing",
    description: "Brand Specialist"
  },
  {
    id: 45,
    username: "nathan.morris",
    firstName: "Nathan",
    lastName: "Morris",
    email: "nathan.morris@example.com",
    birthDate: "1990-12-02",
    basicSalary: 5000000,
    status: "Active",
    group: "Engineering",
    description: "Mobile Developer"
  },
  {
    id: 46,
    username: "audrey.rogers",
    firstName: "Audrey",
    lastName: "Rogers",
    email: "audrey.rogers@example.com",
    birthDate: "1992-09-28",
    basicSalary: 4700000,
    status: "Active",
    group: "HR",
    description: "Benefits Coordinator"
  },
  {
    id: 47,
    username: "isaac.cook",
    firstName: "Isaac",
    lastName: "Cook",
    email: "isaac.cook@example.com",
    birthDate: "1987-04-11",
    basicSalary: 5400000,
    status: "Active",
    group: "Engineering",
    description: "Site Reliability Engineer"
  },
  {
    id: 48,
    username: "claire.morgan",
    firstName: "Claire",
    lastName: "Morgan",
    email: "claire.morgan@example.com",
    birthDate: "1993-01-06",
    basicSalary: 4800000,
    status: "Active",
    group: "Finance",
    description: "Financial Planner"
  },
  {
    id: 49,
    username: "owen.bell",
    firstName: "Owen",
    lastName: "Bell",
    email: "owen.bell@example.com",
    birthDate: "1989-11-19",
    basicSalary: 5200000,
    status: "Active",
    group: "Engineering",
    description: "Frontend Developer"
  },
  {
    id: 50,
    username: "stella.murphy",
    firstName: "Stella",
    lastName: "Murphy",
    email: "stella.murphy@example.com",
    birthDate: "1995-08-03",
    basicSalary: 4400000,
    status: "Active",
    group: "Design",
    description: "Visual Designer"
  },
  {
    id: 51,
    username: "lucas.bailey",
    firstName: "Lucas",
    lastName: "Bailey",
    email: "lucas.bailey@example.com",
    birthDate: "1988-06-27",
    basicSalary: 5300000,
    status: "Active",
    group: "Engineering",
    description: "Backend Developer"
  },
  {
    id: 52,
    username: "nora.rivera",
    firstName: "Nora",
    lastName: "Rivera",
    email: "nora.rivera@example.com",
    birthDate: "1992-03-15",
    basicSalary: 4700000,
    status: "Inactive",
    group: "Operations",
    description: "Operations Manager"
  },
  {
    id: 53,
    username: "caleb.cooper",
    firstName: "Caleb",
    lastName: "Cooper",
    email: "caleb.cooper@example.com",
    birthDate: "1990-01-09",
    basicSalary: 5100000,
    status: "Active",
    group: "Management",
    description: "Scrum Master"
  },
  {
    id: 54,
    username: "lucy.reed",
    firstName: "Lucy",
    lastName: "Reed",
    email: "lucy.reed@example.com",
    birthDate: "1994-12-21",
    basicSalary: 4500000,
    status: "Active",
    group: "Marketing",
    description: "Marketing Analyst"
  },
  {
    id: 55,
    username: "gabriel.bailey",
    firstName: "Gabriel",
    lastName: "Bailey",
    email: "gabriel.bailey@example.com",
    birthDate: "1987-09-05",
    basicSalary: 5500000,
    status: "Active",
    group: "Engineering",
    description: "DevOps Engineer"
  },
  {
    id: 56,
    username: "eleanor.cox",
    firstName: "Eleanor",
    lastName: "Cox",
    email: "eleanor.cox@example.com",
    birthDate: "1993-07-29",
    basicSalary: 4600000,
    status: "Active",
    group: "HR",
    description: "Talent Acquisition Specialist"
  },
  {
    id: 57,
    username: "miles.ward",
    firstName: "Miles",
    lastName: "Ward",
    email: "miles.ward@example.com",
    birthDate: "1989-04-13",
    basicSalary: 5200000,
    status: "Active",
    group: "Engineering",
    description: "Software Developer"
  },
  {
    id: 58,
    username: "violet.price",
    firstName: "Violet",
    lastName: "Price",
    email: "violet.price@example.com",
    birthDate: "1992-02-08",
    basicSalary: 4800000,
    status: "Active",
    group: "Finance",
    description: "Payroll Specialist"
  },
  {
    id: 59,
    username: "felix.sanders",
    firstName: "Felix",
    lastName: "Sanders",
    email: "felix.sanders@example.com",
    birthDate: "1990-10-25",
    basicSalary: 5000000,
    status: "Active",
    group: "Engineering",
    description: "QA Engineer"
  },
  {
    id: 60,
    username: "hazel.ross",
    firstName: "Hazel",
    lastName: "Ross",
    email: "hazel.ross@example.com",
    birthDate: "1995-06-16",
    basicSalary: 4300000,
    status: "Active",
    group: "Design",
    description: "Product Designer"
  },
  {
    id: 61,
    username: "max.watson",
    firstName: "Max",
    lastName: "Watson",
    email: "max.watson@example.com",
    birthDate: "1988-11-30",
    basicSalary: 5200000,
    status: "Active",
    group: "Engineering",
    description: "Backend Developer"
  },
  {
    id: 62,
    username: "penelope.brooks",
    firstName: "Penelope",
    lastName: "Brooks",
    email: "penelope.brooks@example.com",
    birthDate: "1993-05-04",
    basicSalary: 4700000,
    status: "Active",
    group: "Marketing",
    description: "SEO Specialist"
  },
  {
    id: 63,
    username: "oscar.kelly",
    firstName: "Oscar",
    lastName: "Kelly",
    email: "oscar.kelly@example.com",
    birthDate: "1986-08-27",
    basicSalary: 5900000,
    status: "Active",
    group: "Management",
    description: "Director of Engineering"
  },
  {
    id: 64,
    username: "ruby.james",
    firstName: "Ruby",
    lastName: "James",
    email: "ruby.james@example.com",
    birthDate: "1994-03-12",
    basicSalary: 4500000,
    status: "Inactive",
    group: "Design",
    description: "UI Designer"
  },
  {
    id: 65,
    username: "theo.bennett",
    firstName: "Theo",
    lastName: "Bennett",
    email: "theo.bennett@example.com",
    birthDate: "1990-07-08",
    basicSalary: 5100000,
    status: "Active",
    group: "Engineering",
    description: "Frontend Developer"
  },
  {
    id: 66,
    username: "sadie.wood",
    firstName: "Sadie",
    lastName: "Wood",
    email: "sadie.wood@example.com",
    birthDate: "1992-01-23",
    basicSalary: 4800000,
    status: "Active",
    group: "HR",
    description: "HR Manager"
  },
  {
    id: 67,
    username: "hudson.barnes",
    firstName: "Hudson",
    lastName: "Barnes",
    email: "hudson.barnes@example.com",
    birthDate: "1987-12-15",
    basicSalary: 5400000,
    status: "Active",
    group: "Engineering",
    description: "Systems Engineer"
  },
  {
    id: 68,
    username: "willow.gray",
    firstName: "Willow",
    lastName: "Gray",
    email: "willow.gray@example.com",
    birthDate: "1993-09-09",
    basicSalary: 4600000,
    status: "Active",
    group: "Finance",
    description: "Financial Analyst"
  },
  {
    id: 69,
    username: "ezra.hughes",
    firstName: "Ezra",
    lastName: "Hughes",
    email: "ezra.hughes@example.com",
    birthDate: "1989-06-02",
    basicSalary: 5300000,
    status: "Active",
    group: "Engineering",
    description: "Data Scientist"
  },
  {
    id: 70,
    username: "nova.price",
    firstName: "Nova",
    lastName: "Price",
    email: "nova.price@example.com",
    birthDate: "1995-02-19",
    basicSalary: 4400000,
    status: "Active",
    group: "Marketing",
    description: "Digital Marketing Specialist"
  },
  {
    id: 71,
    username: "rowan.long",
    firstName: "Rowan",
    lastName: "Long",
    email: "rowan.long@example.com",
    birthDate: "1988-05-14",
    basicSalary: 5200000,
    status: "Active",
    group: "Engineering",
    description: "Software Developer"
  },
  {
    id: 72,
    username: "aurora.foster",
    firstName: "Aurora",
    lastName: "Foster",
    email: "aurora.foster@example.com",
    birthDate: "1992-11-07",
    basicSalary: 4700000,
    status: "Inactive",
    group: "Design",
    description: "UX Designer"
  },
  {
    id: 73,
    username: "silas.russell",
    firstName: "Silas",
    lastName: "Russell",
    email: "silas.russell@example.com",
    birthDate: "1990-03-31",
    basicSalary: 5000000,
    status: "Active",
    group: "Management",
    description: "Product Owner"
  },
  {
    id: 74,
    username: "iris.olson",
    firstName: "Iris",
    lastName: "Olson",
    email: "iris.olson@example.com",
    birthDate: "1994-08-26",
    basicSalary: 4500000,
    status: "Active",
    group: "Operations",
    description: "Project Coordinator"
  },
  {
    id: 75,
    username: "jasper.elliott",
    firstName: "Jasper",
    lastName: "Elliott",
    email: "jasper.elliott@example.com",
    birthDate: "1987-10-20",
    basicSalary: 5500000,
    status: "Active",
    group: "Engineering",
    description: "Security Engineer"
  },
  {
    id: 76,
    username: "daisy.fisher",
    firstName: "Daisy",
    lastName: "Fisher",
    email: "daisy.fisher@example.com",
    birthDate: "1993-04-03",
    basicSalary: 4600000,
    status: "Active",
    group: "HR",
    description: "Training Manager"
  },
  {
    id: 77,
    username: "milo.harrison",
    firstName: "Milo",
    lastName: "Harrison",
    email: "milo.harrison@example.com",
    birthDate: "1989-01-17",
    basicSalary: 5300000,
    status: "Active",
    group: "Engineering",
    description: "Backend Developer"
  },
  {
    id: 78,
    username: "ivy.fleming",
    firstName: "Ivy",
    lastName: "Fleming",
    email: "ivy.fleming@example.com",
    birthDate: "1992-06-11",
    basicSalary: 4800000,
    status: "Active",
    group: "Finance",
    description: "Budget Manager"
  },
  {
    id: 79,
    username: "elliot.gibson",
    firstName: "Elliot",
    lastName: "Gibson",
    email: "elliot.gibson@example.com",
    birthDate: "1990-09-24",
    basicSalary: 5100000,
    status: "Active",
    group: "Engineering",
    description: "QA Engineer"
  },
  {
    id: 80,
    username: "luna.grant",
    firstName: "Luna",
    lastName: "Grant",
    email: "luna.grant@example.com",
    birthDate: "1995-01-01",
    basicSalary: 4400000,
    status: "Active",
    group: "Design",
    description: "Motion Designer"
  },
  {
    id: 81,
    username: "finn.wallace",
    firstName: "Finn",
    lastName: "Wallace",
    email: "finn.wallace@example.com",
    birthDate: "1988-07-13",
    basicSalary: 5300000,
    status: "Active",
    group: "Engineering",
    description: "Software Developer"
  },
  {
    id: 82,
    username: "cora.mason",
    firstName: "Cora",
    lastName: "Mason",
    email: "cora.mason@example.com",
    birthDate: "1993-12-28",
    basicSalary: 4600000,
    status: "Active",
    group: "Marketing",
    description: "Marketing Coordinator"
  },
  {
    id: 83,
    username: "axel.warren",
    firstName: "Axel",
    lastName: "Warren",
    email: "axel.warren@example.com",
    birthDate: "1986-05-22",
    basicSalary: 5800000,
    status: "Active",
    group: "Management",
    description: "Senior Manager"
  },
  {
    id: 84,
    username: "delilah.dixon",
    firstName: "Delilah",
    lastName: "Dixon",
    email: "delilah.dixon@example.com",
    birthDate: "1994-10-17",
    basicSalary: 4500000,
    status: "Inactive",
    group: "HR",
    description: "HR Specialist"
  },
  {
    id: 85,
    username: "jude.hawkins",
    firstName: "Jude",
    lastName: "Hawkins",
    email: "jude.hawkins@example.com",
    birthDate: "1990-02-09",
    basicSalary: 5200000,
    status: "Active",
    group: "Engineering",
    description: "DevOps Engineer"
  },
  {
    id: 86,
    username: "margot.crawford",
    firstName: "Margot",
    lastName: "Crawford",
    email: "margot.crawford@example.com",
    birthDate: "1992-08-14",
    basicSalary: 4700000,
    status: "Active",
    group: "Design",
    description: "UI/UX Designer"
  },
  {
    id: 87,
    username: "august.fox",
    firstName: "August",
    lastName: "Fox",
    email: "august.fox@example.com",
    birthDate: "1987-11-06",
    basicSalary: 5400000,
    status: "Active",
    group: "Engineering",
    description: "Full Stack Developer"
  },
  {
    id: 88,
    username: "rosalie.hunt",
    firstName: "Rosalie",
    lastName: "Hunt",
    email: "rosalie.hunt@example.com",
    birthDate: "1993-03-29",
    basicSalary: 4800000,
    status: "Active",
    group: "Finance",
    description: "Senior Accountant"
  },
  {
    id: 89,
    username: "atticus.palmer",
    firstName: "Atticus",
    lastName: "Palmer",
    email: "atticus.palmer@example.com",
    birthDate: "1989-05-01",
    basicSalary: 5300000,
    status: "Active",
    group: "Engineering",
    description: "Backend Developer"
  },
  {
    id: 90,
    username: "juniper.black",
    firstName: "Juniper",
    lastName: "Black",
    email: "juniper.black@example.com",
    birthDate: "1995-09-07",
    basicSalary: 4400000,
    status: "Active",
    group: "Marketing",
    description: "Content Creator"
  },
  {
    id: 91,
    username: "felix.wells",
    firstName: "Felix",
    lastName: "Wells",
    email: "felix.wells@example.com",
    birthDate: "1988-04-19",
    basicSalary: 5200000,
    status: "Active",
    group: "Engineering",
    description: "Software Engineer"
  },
  {
    id: 92,
    username: "wren.spencer",
    firstName: "Wren",
    lastName: "Spencer",
    email: "wren.spencer@example.com",
    birthDate: "1992-10-12",
    basicSalary: 4700000,
    status: "Inactive",
    group: "Operations",
    description: "Operations Analyst"
  },
  {
    id: 93,
    username: "hugo.pearson",
    firstName: "Hugo",
    lastName: "Pearson",
    email: "hugo.pearson@example.com",
    birthDate: "1990-01-25",
    basicSalary: 5100000,
    status: "Active",
    group: "Management",
    description: "Project Manager"
  },
  {
    id: 94,
    username: "thea.gardner",
    firstName: "Thea",
    lastName: "Gardner",
    email: "thea.gardner@example.com",
    birthDate: "1994-06-30",
    basicSalary: 4500000,
    status: "Active",
    group: "Design",
    description: "Graphic Designer"
  },
  {
    id: 95,
    username: "otis.johnston",
    firstName: "Otis",
    lastName: "Johnston",
    email: "otis.johnston@example.com",
    birthDate: "1987-08-03",
    basicSalary: 5500000,
    status: "Active",
    group: "Engineering",
    description: "Data Engineer"
  },
  {
    id: 96,
    username: "ada.payne",
    firstName: "Ada",
    lastName: "Payne",
    email: "ada.payne@example.com",
    birthDate: "1993-02-16",
    basicSalary: 4600000,
    status: "Active",
    group: "HR",
    description: "Recruitment Specialist"
  },
  {
    id: 97,
    username: "cyrus.bates",
    firstName: "Cyrus",
    lastName: "Bates",
    email: "cyrus.bates@example.com",
    birthDate: "1989-09-21",
    basicSalary: 5200000,
    status: "Active",
    group: "Engineering",
    description: "Mobile Developer"
  },
  {
    id: 98,
    username: "freya.day",
    firstName: "Freya",
    lastName: "Day",
    email: "freya.day@example.com",
    birthDate: "1992-05-18",
    basicSalary: 4800000,
    status: "Active",
    group: "Finance",
    description: "Finance Manager"
  },
  {
    id: 99,
    username: "lennox.holt",
    firstName: "Lennox",
    lastName: "Holt",
    email: "lennox.holt@example.com",
    birthDate: "1990-11-11",
    basicSalary: 5100000,
    status: "Active",
    group: "Engineering",
    description: "Frontend Developer"
  },
  {
    id: 100,
    username: "maeve.schultz",
    firstName: "Maeve",
    lastName: "Schultz",
    email: "maeve.schultz@example.com",
    birthDate: "1995-04-27",
    basicSalary: 4400000,
    status: "Active",
    group: "Marketing",
    description: "Marketing Specialist"
  }
];